version: "3"

services:
    yarn:
        image: node:14.0.0
        user: node
        working_dir: /home/node/app
        entrypoint: yarn
        command: --help
        volumes:
            - .:/home/node/app

    npm:
        image: node:14.0.0
        user: node
        working_dir: /home/node/app
        entrypoint: npm
        command: --help
        volumes:
            - .:/home/node/app
